# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Code Quality Check

env:
  NODE_VERSION: 20.12.2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "pnpm"
      - name: Install dependencies
        run:
          pnpm install
      - name: Build
        run: pnpm build
      - name: store build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.7.1
      - name: Run Biome
        run: biome ci .

  vitest_tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Run tests
        run: |
          pnpm install
          pnpm test:vitest

  cypress_tests:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - uses: cypress-io/github-action@v4
        with:
          browser: ${{ matrix.browser }}
          build: pnpm build
