# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Build CI

env:
  NODE_VERSION: 16.14.2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "yarn"
      - name: yarn build
        run: |
          yarn install --immutable
          yarn build
      - name: store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint with eslint
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "yarn"
      - name: yarn lint
        run: |
          yarn install --immutable
          yarn eslint . --ext .js,.jsx,.ts,.tsx

  vitest_tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          yarn install --immutable
          yarn test:vitest

  cypress_tests:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - uses: cypress-io/github-action@v4
        with:
          browser: ${{ matrix.browser }}
          build: yarn build
